name = "Opinionated Vanilla-like"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36fdfe43ddc0ec5dc92711e0f86a938200a7e022c699cf099c32410ffaf36b5e"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
