name = "Opinionated Vanilla-like"
author = "bs2kbs2k"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d4288c440a99fbb95a411e71bf3b108ef3941a2269370995874b33eddb4da7f"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
